<?php
declare(strict_types=1);

/**
 * Shopify OAuth installation handler.
 *
 * Visit this page once to authorize the app and obtain a permanent offline
 * Admin API access token.  Re-visit whenever you rotate the app credentials
 * or install the app on a new store — the new token overwrites shopify.ini.
 *
 * Flow:
 *   1. Visit /install.php
 *        → redirects to the Shopify OAuth consent page.
 *   2. Merchant approves the app in Shopify admin.
 *        → Shopify redirects back to /install.php?code=…&hmac=…&shop=…
 *   3. The authorization code is exchanged for a permanent access token.
 *        → Token is written to shopify.ini in the project root.
 *
 * Protected by the same HTTP Basic Auth as the orders/download pages.
 * Requires SHOPIFY_API_KEY, SHOPIFY_API_SECRET, and SHOPIFY_SHOP_DOMAIN
 * to be set in env.ini (or as real environment variables).
 */

$config = require __DIR__ . '/config.php';
require __DIR__ . '/auth.php';

// Protect this page so only you can trigger an installation.
requireBasicAuth($config['auth_user'], $config['auth_password'], 'Shopify Install');

$apiKey     = $config['shopify_api_key'];
$apiSecret  = $config['shopify_api_secret'];
$shopDomain = $config['shopify_shop_domain'];
$iniPath    = $config['shopify_ini_path'];

if ($apiKey === '' || $apiSecret === '' || $shopDomain === '') {
    http_response_code(500);
    exit('SHOPIFY_API_KEY, SHOPIFY_API_SECRET, and SHOPIFY_SHOP_DOMAIN must all be set in env.ini before running the installer.');
}

// Build the absolute callback URL for this script so Shopify can redirect back.
// X-Forwarded-Proto is trusted (proxy headers are considered reliable in this environment).
$forwardedProto = $_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '';
$scheme = $forwardedProto !== '' ? strtolower(explode(',', $forwardedProto)[0]) : ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http');
$callbackUrl = $scheme . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'];

// ── Step 2: OAuth callback — exchange code for access token ──────────────────

if (isset($_GET['code'])) {
    // Verify the HMAC Shopify attaches to the callback to prevent tampering.
    $hmacProvided = (string) ($_GET['hmac'] ?? '');
    $params = $_GET;
    unset($params['hmac']);
    ksort($params);
    $computed = hash_hmac('sha256', http_build_query($params), $apiSecret);

    if (!hash_equals($computed, $hmacProvided)) {
        http_response_code(400);
        exit('Invalid HMAC — possible request tampering detected.');
    }

    // Exchange the authorization code for a permanent offline access token.
    $postBody = http_build_query([
        'client_id'     => $apiKey,
        'client_secret' => $apiSecret,
        'code'          => (string) $_GET['code'],
    ]);

    $context = stream_context_create([
        'http' => [
            'method'        => 'POST',
            'header'        => implode("\r\n", [
                'Content-Type: application/x-www-form-urlencoded',
                'Content-Length: ' . strlen($postBody),
                'Accept: application/json',
            ]),
            'content'       => $postBody,
            'timeout'       => 10,
            'ignore_errors' => true,
        ],
    ]);

    $tokenUrl = sprintf('https://%s/admin/oauth/access_token', $shopDomain);
    $response = @file_get_contents($tokenUrl, false, $context);

    if ($response === false) {
        http_response_code(502);
        exit('Could not reach Shopify token endpoint. Check your server\'s outbound connectivity.');
    }

    $statusLine = $http_response_header[0] ?? '';
    if (!preg_match('#HTTP/\S+\s+(2\d{2})#', $statusLine)) {
        http_response_code(502);
        exit('Shopify returned an error: ' . htmlspecialchars($statusLine) . ' — ' . htmlspecialchars($response));
    }

    try {
        $data = json_decode($response, associative: true, flags: JSON_THROW_ON_ERROR);
    } catch (\JsonException) {
        http_response_code(502);
        exit('Shopify returned invalid JSON from the token endpoint.');
    }

    $token = (string) ($data['access_token'] ?? '');
    if ($token === '') {
        http_response_code(502);
        exit('Shopify did not return an access_token. Response: ' . htmlspecialchars($response));
    }

    // Persist the token to shopify.ini (gitignored).
    $ini  = '; Shopify Admin API access token.' . PHP_EOL;
    $ini .= '; Auto-generated by install.php — do not edit by hand and never commit this file.' . PHP_EOL;
    $ini .= 'SHOPIFY_ACCESS_TOKEN = ' . $token . PHP_EOL;

    if (file_put_contents($iniPath, $ini) === false) {
        http_response_code(500);
        exit('Token was obtained but could not be written to ' . htmlspecialchars($iniPath) . '. Check file-system permissions.');
    }

    header('Content-Type: text/plain; charset=utf-8');
    echo 'Success! Access token saved to shopify.ini.' . PHP_EOL;
    echo 'The webhook is now authorized to call the Shopify Admin API.' . PHP_EOL;
    exit;
}

// ── Step 1: Redirect to Shopify OAuth consent page ───────────────────────────

$authUrl = sprintf(
    'https://%s/admin/oauth/authorize?client_id=%s&scope=%s&redirect_uri=%s',
    $shopDomain,
    rawurlencode($apiKey),
    rawurlencode('read_products'),
    rawurlencode($callbackUrl)
);

header('Location: ' . $authUrl);
exit;
